---

debug: true

gerrit-url: https://review.openstack.org/changes/?q=%s
gerrit-query: status:open+age:4week+(label:Verified<=-1,jenkins+OR+label:Code-Review<=-1)+NOT+label:Workflow<=-1+(project:openstack/swift+OR+project:openstack/python-swiftclient+OR+project:openstack/swift-python-agent+OR+project:openstack/swift-bench+OR+project:openstack/swift-specs)+status:open+NOT+label:Code-Review<=-2&o=DETAILED_ACCOUNTS
sleep: 600

# MySQL settings
host: localhost
port: 3306
database: abandon
user: root
password: master

# logging
log-file: /tmp/abandon.log
log-level: DEBUG
